### ISSUE TITLE
Asset page hanging after updating to 4.1.2

### ISSUE THREAD

**Issue by johnfmorton** [born05/craft-assetusage#44]
I updated a client's site to Asset Usage version 4.1.2 on Craft CMS version 5.4.4. 

After updating, the Assets page would no longer load, and eventually, a "server error" was reported in the control panel. 

No log files were generated during this process, so I have no file to share. 

Since Asset Usage had been updated, I _disabled_ it and the Assets page suddenly loaded as expected. Since disabling it fixed the issue, I have uninstalled it completely from this site. I wanted to report the problem in case others are having the issue and can help track down the cause.

The other plugins used on the site are:

- CKEditor 4.2.0
- Contact Form 3.1.0
- Control Panel CSS 3.0.0
- Cookies 5.0.0
- Entry Editor Links 5.0.0
- FastCGI Cache Bust 5.0.0
- Hyper 2.0.5
- Imager X 5.0.2
- Linkit 5.0.0
- Navigation 3.0.4
- Odds & Ends 5.0.0
- Retour 5.0.3
- SEOmatic 5.1.3
- Sprig 3.5.0
- Table Maker 5.0.2
- Template Comments 5.0.3
- Typogrify 5.0.1
- User Manual 5.0.2
- Vite 5.0.1

**Comment by roelvanhintum** [comment]
@johnfmorton thanks for the heads up! Do you have an error log you can share? It would really help.

**Comment by johnfmorton** [comment]
Unfortunately, I do not have a log file. As I mentioned above, no log file was generated. 

The error happened on multiple environments. I tried to get a log file though. I cleared out all my log files, restarted the server and then I the assets page in the control panel. The site would hang but no log file would be generated.

The site function as expected until I went to the asset panel.

**Comment by SETU-WEB** [comment]
Simiar experience for me using 4.1.3 on Craft 5.6.9.1. The assets page hangs and times out to a server error after a few minutes. Disabled the plugin and it works fine. Checked out the error log and no mention of the plugin but MySQL crashes each time I load the assets page. Removing the plugin stops this error.
 
`An Error occurred while handling another error:
PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away in /var/www/html/vendor/yiisoft/yii2/db/Command.php:1320
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1320): PDOStatement->execute()
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1186): yii\db\Command->internalExecute(NULL)
#2 /var/www/html/vendor/yiisoft/yii2/db/Command.php(417): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /var/www/html/vendor/yiisoft/yii2/db/Query.php(249): yii\db\Command->queryAll()
#4 /var/www/html/vendor/craftcms/cms/src/db/Query.php(292): yii\db\Query->all(NULL)
#5 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(890): craft\db\Query->all()
#6 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(1056): craft\services\Fields->_layouts()
#7 /var/www/html/vendor/craftcms/cms/src/elements/db/ElementQuery.php(2543): craft\services\Fields->getLayoutsByType('craft\\elements\\...')
#8 /var/www/html/vendor/craftcms/cms/src/elements/db/ElementQuery.php(2521): craft\elements\db\ElementQuery->fieldLayouts()
#9 /var/www/html/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1631): craft\elements\db\ElementQuery->customFields()
#10 /var/www/html/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#11 /var/www/html/vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build(Object(craft\elements\db\UserQuery))
#12 /var/www/html/vendor/yiisoft/yii2/db/Query.php(287): yii\db\Query->createCommand(Object(craft\db\Connection))
#13 /var/www/html/vendor/craftcms/cms/src/db/Query.php(320): yii\db\Query->one(NULL)
#14 /var/www/html/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1915): craft\db\Query->one(NULL)
#15 /var/www/html/vendor/craftcms/cms/src/elements/User.php(623): craft\elements\db\ElementQuery->one()
#16 /var/www/html/vendor/yiisoft/yii2/web/User.php(699): craft\elements\User::findIdentity(49391)
#17 /var/www/html/vendor/craftcms/cms/src/web/User.php(520): yii\web\User->renewAuthStatus()
#18 /var/www/html/vendor/yiisoft/yii2/web/User.php(199): craft\web\User->renewAuthStatus()
#19 /var/www/html/vendor/craftcms/cms/src/web/ErrorHandler.php(307): yii\web\User->getIdentity()
#20 /var/www/html/vendor/craftcms/cms/src/web/ErrorHandler.php(168): craft\web\ErrorHandler->showExceptionDetails()
#21 /var/www/html/vendor/yiisoft/yii2/base/ErrorHandler.php(152): craft\web\ErrorHandler->renderException(Object(yii\db\Exception))
#22 /var/www/html/vendor/craftcms/cms/src/web/ErrorHandler.php(102): yii\base\ErrorHandler->handleException(Object(yii\db\Exception))
#23 [internal function]: craft\web\ErrorHandler->handleException(Object(yii\db\Exception))
#24 {main}

Next yii\db\Exception: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
The SQL being executed was: SELECT id, type, uid, config
FROM fieldlayouts
WHERE dateDeleted IS NULL in /var/www/html/vendor/yiisoft/yii2/db/Schema.php:676
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1325): yii\db\Schema->convertException(Object(PDOException), 'SELECT id, t...')
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1186): yii\db\Command->internalExecute('SELECT id, t...')
#2 /var/www/html/vendor/yiisoft/yii2/db/Command.php(417): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /var/www/html/vendor/yiisoft/yii2/db/Query.php(249): yii\db\Command->queryAll()
#4 /var/www/html/vendor/craftcms/cms/src/db/Query.php(292): yii\db\Query->all(NULL)
#5 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(890): craft\db\Query->all()
#6 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(1056): craft\services\Fields->_layouts()
#7 /var/www/html/vendor/craftcms/cms/src/elements/db/ElementQuery.php(2543): craft\services\Fields->getLayoutsByType('craft\\elements\\...')
#8 /var/www/html/vendor/craftcms/cms/src/elements/db/ElementQuery.php(2521): craft\elements\db\ElementQuery->fieldLayouts()
#9 /var/www/html/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1631): craft\elements\db\ElementQuery->customFields()
#10 /var/www/html/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#11 /var/www/html/vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build(Object(craft\elements\db\UserQuery))
#12 /var/www/html/vendor/yiisoft/yii2/db/Query.php(287): yii\db\Query->createCommand(Object(craft\db\Connection))
#13 /var/www/html/vendor/craftcms/cms/src/db/Query.php(320): yii\db\Query->one(NULL)
#14 /var/www/html/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1915): craft\db\Query->one(NULL)
#15 /var/www/html/vendor/craftcms/cms/src/elements/User.php(623): craft\elements\db\ElementQuery->one()
#16 /var/www/html/vendor/yiisoft/yii2/web/User.php(699): craft\elements\User::findIdentity(49391)
#17 /var/www/html/vendor/craftcms/cms/src/web/User.php(520): yii\web\User->renewAuthStatus()
#18 /var/www/html/vendor/yiisoft/yii2/web/User.php(199): craft\web\User->renewAuthStatus()
#19 /var/www/html/vendor/craftcms/cms/src/web/ErrorHandler.php(307): yii\web\User->getIdentity()
#20 /var/www/html/vendor/craftcms/cms/src/web/ErrorHandler.php(168): craft\web\ErrorHandler->showExceptionDetails()
#21 /var/www/html/vendor/yiisoft/yii2/base/ErrorHandler.php(152): craft\web\ErrorHandler->renderException(Object(yii\db\Exception))
#22 /var/www/html/vendor/craftcms/cms/src/web/ErrorHandler.php(102): yii\base\ErrorHandler->handleException(Object(yii\db\Exception))
#23 [internal function]: craft\web\ErrorHandler->handleException(Object(yii\db\Exception))
#24 {main}
Additional Information:
Array
(
    [0] => HY000
    [1] => 2006
    [2] => MySQL server has gone away
)

Previous exception:
PDOException: SQLSTATE[08S01]: Communication link failure: 1053 Server shutdown in progress in /var/www/html/vendor/yiisoft/yii2/db/Command.php:1320
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1320): PDOStatement->execute()
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1186): yii\db\Command->internalExecute(NULL)
#2 /var/www/html/vendor/yiisoft/yii2/db/Command.php(443): yii\db\Command->queryInternal('fetchColumn', 0)
#3 /var/www/html/vendor/yiisoft/yii2/db/Query.php(304): yii\db\Command->queryScalar()
#4 /var/www/html/vendor/craftcms/cms/src/db/Query.php(340): yii\db\Query->scalar(NULL)
#5 /var/www/html/vendor/craftcms/cms/src/services/Users.php(373): craft\db\Query->scalar()
#6 /var/www/html/vendor/craftcms/cms/src/services/Users.php(419): craft\services\Users->getUserPreferences(49391)
#7 /var/www/html/vendor/craftcms/cms/src/base/ApplicationTrait.php(395): craft\services\Users->getUserPreference(49391, 'language')
#8 /var/www/html/vendor/craftcms/cms/src/base/ApplicationTrait.php(360): craft\web\Application->getTargetLanguage(true)
#9 /var/www/html/vendor/craftcms/cms/src/base/ApplicationTrait.php(1590): craft\web\Application->updateTargetLanguage()
#10 /var/www/html/vendor/craftcms/cms/src/web/Application.php(102): craft\web\Application->_preInit()
#11 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#12 /var/www/html/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct(Array)
#13 [internal function]: yii\base\Application->__construct(Array)
#14 /var/www/html/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#15 /var/www/html/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#16 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#17 /var/www/html/vendor/craftcms/cms/src/Craft.php(71): yii\BaseYii::createObject(Array, Array)
#18 /var/www/html/vendor/craftcms/cms/bootstrap/bootstrap.php(343): Craft::createObject(Array)
#19 /var/www/html/vendor/craftcms/cms/bootstrap/web.php(40): require('/var/www/html/v...')
#20 /var/www/html/web/index.php(11): require('/var/www/html/v...')
#21 {main}

Next yii\db\Exception: SQLSTATE[08S01]: Communication link failure: 1053 Server shutdown in progress
The SQL being executed was: SELECT preferences
FROM userpreferences
WHERE userId=49391
LIMIT 1 in /var/www/html/vendor/yiisoft/yii2/db/Schema.php:676
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1325): yii\db\Schema->convertException(Object(PDOException), 'SELECT prefere...')
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1186): yii\db\Command->internalExecute('SELECT prefere...')
#2 /var/www/html/vendor/yiisoft/yii2/db/Command.php(443): yii\db\Command->queryInternal('fetchColumn', 0)
#3 /var/www/html/vendor/yiisoft/yii2/db/Query.php(304): yii\db\Command->queryScalar()
#4 /var/www/html/vendor/craftcms/cms/src/db/Query.php(340): yii\db\Query->scalar(NULL)
#5 /var/www/html/vendor/craftcms/cms/src/services/Users.php(373): craft\db\Query->scalar()
#6 /var/www/html/vendor/craftcms/cms/src/services/Users.php(419): craft\services\Users->getUserPreferences(49391)
#7 /var/www/html/vendor/craftcms/cms/src/base/ApplicationTrait.php(395): craft\services\Users->getUserPreference(49391, 'language')
#8 /var/www/html/vendor/craftcms/cms/src/base/ApplicationTrait.php(360): craft\web\Application->getTargetLanguage(true)
#9 /var/www/html/vendor/craftcms/cms/src/base/ApplicationTrait.php(1590): craft\web\Application->updateTargetLanguage()
#10 /var/www/html/vendor/craftcms/cms/src/web/Application.php(102): craft\web\Application->_preInit()
#11 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#12 /var/www/html/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct(Array)
#13 [internal function]: yii\base\Application->__construct(Array)
#14 /var/www/html/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#15 /var/www/html/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#16 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#17 /var/www/html/vendor/craftcms/cms/src/Craft.php(71): yii\BaseYii::createObject(Array, Array)
#18 /var/www/html/vendor/craftcms/cms/bootstrap/bootstrap.php(343): Craft::createObject(Array)
#19 /var/www/html/vendor/craftcms/cms/bootstrap/web.php(40): require('/var/www/html/v...')
#20 /var/www/html/web/index.php(11): require('/var/www/html/v...')
#21 {main}
Additional Information:
Array
(
    [0] => 08S01
    [1] => 1053
    [2] => Server shutdown in progress
)`


`

**Comment by andrewmenich** [comment]
I'm having the same experience and the slowdown seems to be on the `queryContents()` method, which outputs a query like this: 

```sql
SELECT `elementId` AS `id`, `siteId`
FROM `elements_sites`
WHERE (`content` LIKE '%asset:349764:%') OR (`content` LIKE '%\"imageId\": \"349764\",%')
```

Running that on my database locally takes on average 2.75 seconds where my `elements_sites` table has ~218,000 rows. On an asset index page with 100 assets, this makes it unusable. Obviously not a fault of the plugin as there are underlying constrains with the database. However, if the plugin could have an option to enable/disable the content querying that might be helpful.

**Comment by adam-webdna** [comment]
As a work around we have found you don't actually need to uninstall or disable the plugin. By unchecking the usage column from the assets dashboard in the cms, the assets load in "normal' time. Defeats the point of the plugin a bit, but means you could still potentially use on a page by page basis. Would be great to get this fixed though.
